# Generated by Django 6.0.4 on 2026-05-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('course_duration', models.IntegerField()),
                ('trainer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=150)),
                ('project_title', models.CharField(max_length=200)),
                ('project_category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('contact', models.IntegerField()),
                ('age', models.IntegerField()),
                ('course', models.CharField(max_length=50)),
                ('socio_professional_category', models.CharField(max_length=50)),
                ('current_address', models.CharField(max_length=150)),
                ('region', models.CharField(max_length=100)),
                ('level_of_education', models.CharField(max_length=100)),
            ],
        ),
    ]
