# Generated by Django 6.0.4 on 2026-05-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=100)),
                ('pillar', models.CharField(max_length=100)),
                ('name_of_beneficiaries', models.CharField(max_length=100)),
                ('number_of_beneficiaries', models.IntegerField()),
                ('number_of_male', models.IntegerField()),
                ('number_of_female', models.IntegerField()),
                ('region', models.CharField(max_length=100)),
                ('implementing_partner', models.CharField(max_length=150)),
            ],
        ),
    ]
